on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:alpine3.20
        env:
          POSTGRES_DB: task_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd="pg_isready -U user -d task_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      elasticsearch:
        image: elasticsearch:7.17.16
        options: >-
          --health-cmd="curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
        env:
          discovery.type: single-node
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for DB to be ready
      run: |
        until pg_isready -h db -U user; do
          sleep 1
        done

    - name: Wait for Elasticsearch to be ready
      run: |
        until curl -s http://elasticsearch:9200/_cluster/health | grep -vq '"status":"red"'; do
          sleep 1
        done

    - name: Run migrations
      run: python manage.py migrate

    - name: Run tests
      run: pytest

# name: Django CI

# on:
#   push:
#     branches: [ main ] # Adjust branch names as needed
#   pull_request:
#     branches: [ main ] 

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Run docker-compose
#         uses: hoverkraft-tech/compose-action@v2.0.1
#         with:
#           compose-file: "./docker-compose.yml"

#       - name: Run migrations and tests
#         run: |
#           docker-compose exec web python manage.py migrate
#           docker-compose exec web python manage.py test # Or your test command

#       - name: Stop Services (docker-compose)
#         if: always()
#         run: docker-compose down