name: Docker Compose Action

on: [push]

env:
  POSTGRES_DB: "task_db"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: 5432

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y


      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
        env:
          POSTGRES_DB: "task_db"
          POSTGRES_USER: "user"
          POSTGRES_PASSWORD: "password"
          POSTGRES_HOST: "db"
          POSTGRES_PORT: 5432

      - name: Execute tests in the running services
        run: |
          docker-compose exec web pytest
        env:
          POSTGRES_DB: "task_db"
          POSTGRES_USER: "user"
          POSTGRES_PASSWORD: "password"
          POSTGRES_HOST: "db"
          POSTGRES_PORT: 5432